config/routes.rb
require 'resque/server'
require "sidekiq/web"
ReadersDoor::Application.routes.draw do
  root :to => "website#home"

  resources :facebooks

  mount SecureResqueServer.new, :at => '/resque'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == "readersdoor" && password == "rdadminontheroll"
  end 
  mount Sidekiq::Web => '/sidekiq'  

  resources :tags

  resources :categories

  resources :movies

  resources :prizes

  resources :books

  resources :edges

  resources :human_profiles

  resources :chat_messages

  resources :website

  get 'how_it_works'                => 'website#how_it_works',  :as => 'how_it_works'
  get 'publishers'                  => 'website#publishers',    :as => 'publishers'
  get 'recommended_books'     => "recommendations#books",    :as => "recommended_books"
  get 'recommendations'          => "recommendations#index",    :as => "recommendations"

  get 'random_quote'             => "website#random_quote",    :as => "random_quote"
  get 'ads'                      => "website#ads",             :as => "ads"
  get 'coming_soon'              => "website#coming_soon",     :as => "coming_soon"
  get "invalid_user"             => "users#invalid_user",      :as => "invalid_user"
  post "books/find_by_isbn"      => "books#find_by_isbn",      :as => "find_book_by_isbn"
  post "books/remove_tag"        => "books#remove_tag",        :as => "remove_tag_for_book"
  post "books/add_tag"           => "books#add_tag",           :as => "add_tag_for_book"
  get "search_books"             => "books#search_book",       :as => "search_books"
  get "tags_by_chr"              => "tags#get_by_chr",         :as => "tags_by_chr"
  get "logs_by_tag"              => "logs#get_by_tag",         :as => "logs_by_tag"
  get "logs_by_user"             => "logs#get_by_user",        :as => "logs_by_user"
  get "logout"                   => "users#logout",            :as => "logout_user"
  get "add_tag_to_subcategory"   => "tags#map",                :as => "add_tag_to_subcategory"
  get "remove_tag_from_subcategory" => "tags#unmap",           :as => "remove_tag_from_subcategory"
  get "test"                     => "users#test",              :as => "test"
  get "activate"                 => "users#activate",          :as => "activate"
  

  get "new_child_category"      => "categories#new_child_category", :as => "new_child_category"
  post "add_child_category"     => "categories#add_child_category", :as => "add_child_category"
  post "email_subscription"     => "website#email_subscription",    :as => "email_subscription"

  get  "freebase"                => "tests#freebase",                  :as => "freebase"
  get  "freebase_search"         => "tests#freebase_search",           :as => "freebase_search"
  get  "freebase_resource"       => "tests#freebase_resource",         :as => "freebase_resource"
  get "horizontal_scroll"        => "tests#horizontal_scroll",         :as => "horizontal_scroll"
  get "angular_test"             => "tests#angular_test",              :as => "angular_test"

  get "verify"                   => "users#verify",                   :as => "verify"   
  get "book_count"               => "books#count",                    :as => "get_book_count"
  get 'home'                      => "website#home",                  :as => "home"
  get 'new_home'                      => "website#new_home",          :as => "new_home"
  get 'filters'                   => "website#filters",               :as => "filters"
  get 'search'                    => "website#search",                :as => "search"
  get 'profile'                   => "website#profile",               :as => "profile"
  
  get 'book'                      => "website#book",                  :as => "dev_book"
  get 'authors'                   => "website#authors",            :as => "authors"
  get 'network'                   => "website#network",               :as => "network"
  get 'journey'                   => "website#journey",               :as => "journey"
  get 'customise'                 => "website#customise",             :as => "customise"
  get 'author'                    => "website#author",                :as => "author"
  get 'room'                      => "website#room",                  :as => "room"
  get 'news'                      => "website#news",                  :as => "news"
  get 'news_group'                => "website#news_group",            :as => "news_group"
  get 'quiz'                      => "website#quiz",                  :as => "quiz"

  get 'tree'                      => "categories#show_tree",    :as => "show_tree"
  get 'search_tag'                => "tags#search_tag",         :as => "search_tag"
  get 'search_book'               => "books#search_book",       :as => "search_book"

  get "panel/feedbacks"                 => "users#feedbacks",                   :as => "feedbacks"   
  get "change_feedback_status"          => "users#change_feedback_status",      :as => "change_feedback_status"   
  
  get "panel/labels"                    => "books#labels",                      :as => "labels"   
  get "panel/trends"                    => "books#trends",                      :as => "trends"   
  get "panel/grids"                     => "books#grids",                       :as => "grids"   
  get "panel/thumbs"                    => "books#thumbs",                      :as => "thumbs"
  get "delete_grid"                     => "books#delete_grid",                 :as => "delete_grid"
  get "add_grid"                        => "books#add_grid",                    :as => "add_grid"
  get "update_grid"                     => "books#update_grid",                 :as => "update_grid"
  get "update_thumb_status"             => "books#update_thumb_status",         :as => "update_thumb_status"
  get "add_label"                       => "books#add_label",                   :as => "add_label"
  get "remove_label"                    => "books#remove_label",                :as => "remove_label"
  get "clear_data"                      => "users#clear_data",                  :as => "clear_data"
  get "reset_grid_links"                => "books#reset_grid_links",            :as => "reset_grid_links"
  get "book_detail"                     => "books#book_detail",                 :as => "book_detail"
  get "trending_new_books"              => "books#trending_new_books",          :as => "trending_new_books"
  get "cover_photos"                    => "books#cover_photos",                :as => "cover_photos"
  get "upload_cover_photo"              => "books#upload_cover_photo",          :as => "upload_cover_photo"
  get "set_active_cover_photo"          => "books#set_active_cover_photo",      :as => "set_active_cover_photo"
  
  get "recover_password"                => "users#recover_password",            :as => "recover_password"
  get "save_password"                   => "users#save_password",               :as => "save_password"
  get "all_users"                       => "users#all",                         :as => "all_users"
  get "update_user"                     => "users#update",                         :as => "update_user"
  get 'users'                           => "users#index",                       :as => "users"
  post "data"                           => "books#data",                        :as => "data"
  get "remove_trend"                    => "books#remove_trend",                :as => "remove_trend"
  get "invite"                          => "users#invite",                      :as => "invite"

  get 'signup'                          => "website#signup",                    :as => "signup"

  get 'blogs'                           => "website#blogs",                     :as => "blogs"
  get 'communities'                     => "website#communities",               :as => "communities"
  get 'personalised_suggestions'        => "website#personalised_suggestions",  :as => "personalised_suggestions"

  get 'signup'                          => "website#signup",                    :as => "signurep"
  get 'rooms'                      => "website#rooms",                :as => "rooms"

  get "trending_community_books"        => "books#trending_community_books",     :as => "trending_community_books"
  get "delete_book_relationship"        => "books#delete_book_relationship",       :as => "delete_book_relationship"
  get "help"                           => "website#help",                        :as => "help"
  get "vision"                           => "website#vision",                        :as => "vision"
  get "about"                           => "website#about",                        :as => "about"
  get "work"                              => "website#work",                        :as => "work"
  get "data_analytics"                   => "website#data_analytics",            :as => "data_analytics"
  get "testimonials"                   => "website#testimonials",            :as => "testimonials"
  post 'webhooks'                        => "website#webhooks",                  :as => "webhooks"

  get 'games'                         => "website#games",                 :as => "games"

  get "odit_book"                   => "odit#book",            :as => "odit_book"
  get "odit_filters"                   => "odit#filters",            :as => "odit_filters"
  get "odit_author"                   => "odit#author",            :as => "odit_author"
  get "odit_room"                   => "odit#room",            :as => "odit_room"
  get "odit_rooms"                   => "odit#rooms",            :as => "odit_rooms"
  get "odit_profile"                   => "odit#profile",            :as => "odit_profile"
  get "utilities"                       => "website#utilities",          :as => "utilities"

end

app/views/shared/_advertisements.html.erb
<iframe src="http://www.flipkart.com/affiliate/displayWidget?affrid=WRID-138765371846256883" frameborder="0" height="250" width="300" style="
    float: right;
    margin-right: 15px;
    margin-top: 15px;
"></iframe>
<iframe src='http://www.flipkart.com/affiliate/displayWidget?affrid=WRID-138765432268739266' frameborder=0 height=90 width=728></iframe>
<iframe src='http://www.flipkart.com/affiliate/displayWidget?affrid=WRID-138280734532168369' height=55 width=660 scrolling='no' frameborder=0></iframe>

app/views/shared/_facebook_share.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=189161627946475";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_favicon.html.erb
<link rel="icon" 
      type="image/png" 
      href="/assets/favicon.ico">

app/views/shared/_header.html.erb
<div class="main-header">
	<span class="tab-group">
		<a href="/" target="_blank">ReadersDoor</a>
		<a href="<%= users_path %>" class="tab-center">Users</a>
		<a href="<%= trends_path %>" class="tab-center">Trends</a>
		<a href="<%= grids_path %>" class="tab-center">Grids</a>
		<a href="<%= thumbs_path %>" class="tab-center">Thumbs</a>
		<a href="<%= labels_path %>" class="tab-center">Labels</a>
		<a href="<%= feedbacks_path %>" class="tab-center">Feedbacks</a>
		<a href="<%= categories_path %>" class="tab-center">Categories</a>
		<a href="<%= tags_path %>" class="tab-center">Star Genres</a>
		<a href="<%= movies_path %>" class="tab-center">Movies</a>
		<a href="<%= cover_photos_path %>" class="tab-center">Cover Photos</a>
	    <a href="https://drive.google.com/folderview?id=0B2XvzrkA012saWJJNHN1SjBpbWM&usp=sharing" target="_blank" class="tab-center">Drive</a>
	</span>
    
    <%#= @message %>
	<!-- <a class="tab-right" href="<%= logout_user_path %>"> -->
	    <!-- Logout -->
	<!-- </a> -->
	<!-- Hi <%#= @user.human_profile.name %> -->
	<%# if @user %>
	<%# else %>
		<%#= @message %>
		<!-- <a class="tab-right" href="<%#= user_omniauth_authorize_path(:google_oauth2) %>"> -->
		    <!-- Login with Google -->
		<!-- </a> -->
	<%# end %>
</div>

app/views/shared/_meta_tags.html.erb
<meta property="og:type" content="website" />
<meta property="og:image" content="http://www.readersdoor.com/assets/collage2.jpg" />
<meta property="og:title" content="ReadersDoor" />
<meta property="og:url" content="http://www.readersdoor.com/" />
<meta property="og:description" content="Find your next read, know your books, meet similar readers, follow authors, read online, share books." />
<meta property="og:site_name" content="ReaderDoor.com" />

app/views/shared/_responsive.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>

app/views/shared/_search_box.html.erb
<%= form_tag(find_book_by_isbn_path, :method => :post, :class => "search_box") do %>
	<%= label_tag :book, :isbn %>
  	<%= text_field_tag :book, :isbn, :value => @isbn_number %>
  	<%= submit_tag 'Search', :class => "search_button"%>
<% end %>