config/routes.rb
require 'resque/server'
require "sidekiq/web"
ReadersDoor::Application.routes.draw do
  root :to => "website#home"

  resources :facebooks

  mount SecureResqueServer.new, :at => '/resque'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == "readersdoor" && password == "rdadminontheroll"
  end 
  mount Sidekiq::Web => '/sidekiq'  

  resources :tags

  resources :categories

  resources :movies

  resources :prizes

  resources :books

  resources :edges

  resources :human_profiles

  resources :chat_messages

  resources :website

  get 'how_it_works'                => 'website#how_it_works',  :as => 'how_it_works'
  get 'publishers'                  => 'website#publishers',    :as => 'publishers'
  get 'recommended_books'     => "recommendations#books",    :as => "recommended_books"
  get 'recommendations'          => "recommendations#index",    :as => "recommendations"

  get 'random_quote'             => "website#random_quote",    :as => "random_quote"
  get 'ads'                      => "website#ads",             :as => "ads"
  get 'coming_soon'              => "website#coming_soon",     :as => "coming_soon"
  get "invalid_user"             => "users#invalid_user",      :as => "invalid_user"
  post "books/find_by_isbn"      => "books#find_by_isbn",      :as => "find_book_by_isbn"
  post "books/remove_tag"        => "books#remove_tag",        :as => "remove_tag_for_book"
  post "books/add_tag"           => "books#add_tag",           :as => "add_tag_for_book"
  get "search_books"             => "books#search_book",       :as => "search_books"
  get "tags_by_chr"              => "tags#get_by_chr",         :as => "tags_by_chr"
  get "logs_by_tag"              => "logs#get_by_tag",         :as => "logs_by_tag"
  get "logs_by_user"             => "logs#get_by_user",        :as => "logs_by_user"
  get "logout"                   => "users#logout",            :as => "logout_user"
  get "add_tag_to_subcategory"   => "tags#map",                :as => "add_tag_to_subcategory"
  get "remove_tag_from_subcategory" => "tags#unmap",           :as => "remove_tag_from_subcategory"
  get "test"                     => "users#test",              :as => "test"
  get "activate"                 => "users#activate",          :as => "activate"
  

  get "new_child_category"      => "categories#new_child_category", :as => "new_child_category"
  post "add_child_category"     => "categories#add_child_category", :as => "add_child_category"
  post "email_subscription"     => "website#email_subscription",    :as => "email_subscription"

  get  "freebase"                => "tests#freebase",                  :as => "freebase"
  get  "freebase_search"         => "tests#freebase_search",           :as => "freebase_search"
  get  "freebase_resource"       => "tests#freebase_resource",         :as => "freebase_resource"
  get "horizontal_scroll"        => "tests#horizontal_scroll",         :as => "horizontal_scroll"
  get "angular_test"             => "tests#angular_test",              :as => "angular_test"

  get "verify"                   => "users#verify",                   :as => "verify"   
  get "book_count"               => "books#count",                    :as => "get_book_count"
  get 'home'                      => "website#home",                  :as => "home"
  get 'new_home'                      => "website#new_home",          :as => "new_home"
  get 'filters'                   => "website#filters",               :as => "filters"
  get 'search'                    => "website#search",                :as => "search"
  get 'profile'                   => "website#profile",               :as => "profile"
  
  get 'book'                      => "website#book",                  :as => "dev_book"
  get 'authors'                   => "website#authors",            :as => "authors"
  get 'network'                   => "website#network",               :as => "network"
  get 'journey'                   => "website#journey",               :as => "journey"
  get 'customise'                 => "website#customise",             :as => "customise"
  get 'author'                    => "website#author",                :as => "author"
  get 'room'                      => "website#room",                  :as => "room"
  get 'news'                      => "website#news",                  :as => "news"
  get 'news_group'                => "website#news_group",            :as => "news_group"
  get 'quiz'                      => "website#quiz",                  :as => "quiz"

  get 'tree'                      => "categories#show_tree",    :as => "show_tree"
  get 'search_tag'                => "tags#search_tag",         :as => "search_tag"
  get 'search_book'               => "books#search_book",       :as => "search_book"

  get "panel/feedbacks"                 => "users#feedbacks",                   :as => "feedbacks"   
  get "change_feedback_status"          => "users#change_feedback_status",      :as => "change_feedback_status"   
  
  get "panel/labels"                    => "books#labels",                      :as => "labels"   
  get "panel/trends"                    => "books#trends",                      :as => "trends"   
  get "panel/grids"                     => "books#grids",                       :as => "grids"   
  get "panel/thumbs"                    => "books#thumbs",                      :as => "thumbs"
  get "delete_grid"                     => "books#delete_grid",                 :as => "delete_grid"
  get "add_grid"                        => "books#add_grid",                    :as => "add_grid"
  get "update_grid"                     => "books#update_grid",                 :as => "update_grid"
  get "update_thumb_status"             => "books#update_thumb_status",         :as => "update_thumb_status"
  get "add_label"                       => "books#add_label",                   :as => "add_label"
  get "remove_label"                    => "books#remove_label",                :as => "remove_label"
  get "clear_data"                      => "users#clear_data",                  :as => "clear_data"
  get "reset_grid_links"                => "books#reset_grid_links",            :as => "reset_grid_links"
  get "book_detail"                     => "books#book_detail",                 :as => "book_detail"
  get "trending_new_books"              => "books#trending_new_books",          :as => "trending_new_books"
  get "cover_photos"                    => "books#cover_photos",                :as => "cover_photos"
  get "upload_cover_photo"              => "books#upload_cover_photo",          :as => "upload_cover_photo"
  get "set_active_cover_photo"          => "books#set_active_cover_photo",      :as => "set_active_cover_photo"
  
  get "recover_password"                => "users#recover_password",            :as => "recover_password"
  get "save_password"                   => "users#save_password",               :as => "save_password"
  get "all_users"                       => "users#all",                         :as => "all_users"
  get "update_user"                     => "users#update",                         :as => "update_user"
  get 'users'                           => "users#index",                       :as => "users"
  post "data"                           => "books#data",                        :as => "data"
  get "remove_trend"                    => "books#remove_trend",                :as => "remove_trend"
  get "invite"                          => "users#invite",                      :as => "invite"

  get 'signup'                          => "website#signup",                    :as => "signup"

  get 'blogs'                           => "website#blogs",                     :as => "blogs"
  get 'communities'                     => "website#communities",               :as => "communities"
  get 'personalised_suggestions'        => "website#personalised_suggestions",  :as => "personalised_suggestions"

  get 'signup'                          => "website#signup",                    :as => "signurep"
  get 'rooms'                      => "website#rooms",                :as => "rooms"

  get "trending_community_books"        => "books#trending_community_books",     :as => "trending_community_books"
  get "delete_book_relationship"        => "books#delete_book_relationship",       :as => "delete_book_relationship"
  get "help"                           => "website#help",                        :as => "help"
  get "vision"                           => "website#vision",                        :as => "vision"
  get "about"                           => "website#about",                        :as => "about"
  get "work"                              => "website#work",                        :as => "work"
  get "data_analytics"                   => "website#data_analytics",            :as => "data_analytics"
  get "testimonials"                   => "website#testimonials",            :as => "testimonials"
  post 'webhooks'                        => "website#webhooks",                  :as => "webhooks"

  get 'games'                         => "website#games",                 :as => "games"

  get "odit_book"                   => "odit#book",            :as => "odit_book"
  get "odit_filters"                   => "odit#filters",            :as => "odit_filters"
  get "odit_author"                   => "odit#author",            :as => "odit_author"
  get "odit_room"                   => "odit#room",            :as => "odit_room"
  get "odit_rooms"                   => "odit#rooms",            :as => "odit_rooms"
  get "odit_profile"                   => "odit#profile",            :as => "odit_profile"
  get "utilities"                       => "website#utilities",          :as => "utilities"

end

app/models/category.rb
class Category < Neo
	def initialize id
		@id = id
		# TODO
		# first book in category
		# @first_book
	end

	def match
		" MATCH (category:Category) WHERE ID(category) = " + @id.to_s + " WITH category "
	end

	def self.basic_info node_variable="category"
		" ID("+node_variable+") AS "+node_variable+"_id, "+node_variable+".icon AS "+node_variable+"_icon, "+node_variable+".name AS "+node_variable+"_name, "+node_variable+".aws_key AS "+node_variable+"_aws_key, "+node_variable+".uuid AS "+node_variable+"_uuid"
	end

	def self.grouped_basic_info node_variable="category"
		" {id: ID("+node_variable+"), icon: "+node_variable+".icon, name: "+node_variable+".name, aws_key: "+node_variable+".aws_key, uuid: "+node_variable+".uuid} "
	end

	def self.order_desc
		" ORDER BY likes.weight DESC"
	end

	def self.likes_weight
		", likes.weight AS likes_weight "
	end

	def self.match_books_in_list node_variable="category", skip, length
		" MATCH (" + node_variable + ")-[next_in_category:NextInCategory*" + skip.to_s + "]->(book:Book) WITH book, "+node_variable+" MATCH path = (book)-[next_in_category:NextInCategory*" + length.to_s + "]->(category_book:Book) WHERE ALL(relation IN relationships(path) WHERE relation.uuid = "+node_variable+".uuid) WITH "+node_variable+", EXTRACT(n in nodes(path)|n) AS books UNWIND books AS book "
	end

	def self.books_for_user node_variable="category", skip, length
		" MATCH (" + node_variable + ")-[next_in_category:NextInCategory*" + skip.to_s + "]->(book:Book) WITH book, "+node_variable+", user MATCH path = (book)-[next_in_category:NextInCategory*" + length.to_s + "]->(category_book:Book) WHERE ALL(relation IN relationships(path) WHERE relation.uuid = "+node_variable+".uuid) WITH "+node_variable+", user, EXTRACT(n in nodes(path)|n) AS books UNWIND books AS book "
	end

	def match_nth_book skip
		" MATCH (book:Book)-[:NextInCategory*.."+skip.to_s+"]->(nth_book) WHERE ID(book)="+@first_book.to_s+" WITH nth_book as book "
	end

	def match_books_after skip, count
		match_nth_book(skip) + " MATCH path=(book)-[:NextInCategory*.."+count.to_s+"]->(last_book) WITH EXTRACT (n IN nodes(path)|n) AS books UNWIND books AS book  "
	end

	def self.match_books category="category"
		" MATCH ("+category+":Category)-[:FromCategory]-(book) WITH "+category+", book "
	end

	def match_books category="category"
		" MATCH ("+category+":Category)-[:FromCategory]-(book:Book) WHERE ID("+category+") = " + @id.to_s + " WITH "+category+", book "
	end
end

app/models/category/root.rb
class Category::Root < Category

	def self.match_books_root
		" MATCH (book)-[:FromCategory]->(:Category)-[:HasRoot*0..1]->(root_category:Category{is_root:true}) WITH book, root_category "
	end

	def self.optional_match_books_root
		" OPTIONAL " + Category::Root.match_books_root 
	end

	def self.match
		" MATCH (root_category:Category{is_root:true}) WITH root_category "
	end

	def self.basic_info
		super("root_category")
	end

	def self.match_books
		super("root_category")
	end

	def self.match_books_in_list skip, length
		super("root_category", skip, length)
	end

	def self.books_for_user skip, length
		super("root_category", skip, length)
	end

	def self.get_all
		" MATCH (root_category:Category{is_root:true}) " + Category::Root.return_group(self.basic_info)
	end

	def self.grouped_basic_info
		super("root_category")
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    neo = Neography::Rest.new

    clause = "MATCH (c:Category)-[:HasChild]->(child:Category) WHERE c.is_root=true RETURN c.name, c.icon, COUNT(child)"
    puts clause.blue.on_red
    @categories = neo.execute_query(clause)["data"]
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    render 'show', :status => 200, :layout => false
  end

  # GET /categories/new
  def new
    @category = Category.new
    render 'new', :status => 200, :layout => false
  end

  # GET /categories/1/edit
  def edit
    render 'edit', :status => 200, :layout => false
  end

  # POST /categories
  # POST /categories.json
  def create
    parent_id = params[:parent_id]
    if parent_id
      @category = Category.new(category_params.except(:edge))
      @edge = Edge.new(:weight => category_params[:edge][:weight])
      @parent_category = Category.find(parent_id)
      if @parent_category.children.create category_params.except(:edge)
        @category.id = @parent_category.children.where(:name => category_params[:name].upcase).first.id
        @edge.update_attributes(:start_node_id => parent_id.to_i, :end_node_id => @category.id)
        render :json => {:message => 'Category was successfully created.', :parent_id => parent_id, :id => @category.id, :name => @category.name}, :status => 200, :layout => false
      else
        render :json => {:message => 'Category failed to create.'}, :status => 400, :layout => false
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    unless @category.name == "ROOT"
      if @category.update(category_params)
        render 'show', :status => 200, :layout => false, notice: 'Category was successfully created.'
      else
        render :json => {:message => "Error in updating category"}, notice: @category.errors, :layout => false, :status => 400
      end
    else
      render :json => {:message => "Root can't be edited."}, :layout => false, :status => 400
    end
  end

  def show_tree
    @root = ShelfariCategory.where(:name => params[:name]).first rescue ShelfariCategory.where(:name => "ROOT").first
    render 'show_tree'
  end

  def new_child_category
    @parent_id = params[:parent_id]
    @category = Category.new
    @parent_category = Category.find(@parent_id)
    render 'new_child', :layout => false, :status => 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params[:category]
    end

end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, :remote => true, :html => {:class => "form-horizontal category", novalidate:false}) do |f| %>
    <%= f.error_notification %>
  <div class="modal-body form-inputs">
    <%= f.input :name,
                :input_html => {
                  :required => true
                } %>
    
  </div>

  <div class="form-actions modal-footer">
    <%= f.button :submit, :class => "btn-inverse" %>
  </div>
<% end %>

app/views/categories/_node.html.erb
<span>
	<div class="node span" id="node_<%= @root.id %>" onclick="open_modal($(this));" title="Click to Enter a Child" style="<% if @root.name == 'ROOT'%>background-color:rgb(255, 102, 0);<% end %>">
		<%= @root.name %>
	</div>
	<div class="node_edit span" id="node_edit_<%= @root.id %>" onclick="open_edit_modal($(this))" title="Edit">
		<icon class="icon-edit"></icon>
	</div>
	<div class="node_toggle span" id="node_toggle_<%= @root.id %>" onclick="toggle_tree($(this))" title="Toggle">
		<icon class="icon-leaf"></icon>
	</div>
</span>

app/views/categories/_show_sub_tree.html.erb
<div class="category_tree span">
	<%= render :partial => "node" %>
	<br/>
	<span class="children" id="children_of_<%= @root.id %>">
		<% if @root.has_children? %>
			<% @root.children.each do |child| %>
				<%= render :partial => "show_sub_tree", :locals => {:@root => child} %>
			<% end %>
		<% end %>
	</span>
</div>
<script type="text/javascript">
	$('.node').on('mouseover', function(){
		var id = $(this).attr('id').split("node_")[1]
		var children_id = "children_of_"+id
		$('#'+children_id+' div div').addClass('highlight_children') 
	})
	$('.node').on('mouseout', function(){
		var id = $(this).attr('id').split("node_")[1]
		var children_id = "children_of_"+id
		$('#'+children_id+' div div').removeClass('highlight_children')	
	})
</script>

app/views/categories/edit.html.erb
<%= render 'form' %>

app/views/categories/index.html.erb
<table>
  <tr>
    <th>S.No.</th>
    <th>Name</th>
    <th>#Children</th>
    <th>Active</th>
    <th>Submit</th>
  </tr>
  <% @categories.each_with_index do |category, index|%>
    <tr>
      <td><%= index %></td>
      <td><%= category[0] %></td>
      <td><%= category[2] %></td>
    </tr>
  <% end %>
</table>
<div class="main_footer">
  CATEGORIES
</div>

<div class="vertical_padder"></div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/new_child.html.erb
<%= simple_form_for(@category, :remote => true, :html => {:class => "form-horizontal category", novalidate:false}) do |f| %>
    <%= f.error_notification %>
  <div class="modal-body form-inputs">
  	<%= hidden_field_tag :parent_id, @parent_id %>
  	<%= f.input :name,
                :input_html => {
                  :placeholder => @parent_category.name+"'s child category",
                  :required => true
                } %>
  	<%= f.simple_fields_for :edge do |c| %>
  		<%= c.input :weight,
                :input_html => {
                  :placeholder => "Give a connection weight."
                  } %>
  	<% end %>
    
  </div>

  <div class="form-actions modal-footer">
    <%= f.button :submit, :class => "btn-inverse" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show_tree.html.erb
<%= render :partial => "show_sub_tree", :locals => {:@root => @root}%>
<%= render :partial => "shared/modals/modal_box", :locals => {:modal_id => "addChildCategoryModal",
																:modal_label => "addChildCategoryLabel",
																:modal_head => "Add Child Category"}%>
<%= render :partial => "shared/modals/modal_box", :locals => {:modal_id => "editCategoryModal",
																:modal_label => "editCategoryLabel",
																:modal_head => "Edit Category"}%>

<script>
	function open_modal($this){
		var id = $this.attr('id').split('node_')[1];
		var url = "<%= new_child_category_path %>";
		$.ajax({
			url: url,
			data: "parent_id="+id,
			success: function(data, textStatus, jqXHR){
				$('#addChildCategoryModal .content').html(data)
				$('#addChildCategoryModal').modal();
			},
			error: function(jqXHR, textStatus, errorThrown){
				alert("Something went wrong.")
			}
		});
	}

	function open_edit_modal($this){
		var id = $this.attr('id').split('node_edit_')[1];
		var url = "/categories/"+id+"/edit";
		$.ajax({
			url: url,
			data: "id="+id,
			success: function(data, textStatus, jqXHR){
				$('#editCategoryModal .content').html(data);
				$('#editCategoryModal').modal();
			},
			error: function(jqXHR, textStatus, errorThrown){
				alert("Something went wrong.")
			}
		})
	}

	function toggle_tree($this){
		var id = $this.attr('id').split('node_toggle_')[1];
		$('#children_of_'+id).toggle();
		// var url = "/categories/"+id+"/edit";
	}

	$('#addChildCategoryModal').on('ajax:success', function(jqXHR, data, textStatus){
		$('#addChildCategoryModal').modal('hide')
		window.location.reload()
	})
	$('#addChildCategoryModal').on('ajax:error', function(jqXHR, data, textStatus){
		alert(data.responseJSON["message"]);
	})

	$('#editCategoryModal').on('ajax:success', function(jqXHR, data, textStatus){
		$('#editCategoryModal').modal('hide')
		window.location.reload()
	})
	$('#editCategoryModal').on('ajax:error', function(jqXHR, data, textStatus){
		alert(data.responseJSON["message"]);
	})
</script>